DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE photos (
  id SERIAL PRIMARY KEY,
  filename VARCHAR(255),
  mimetype VARCHAR(255),
  path VARCHAR(255)
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  photo_id INTEGER REFERENCES photos(id)
);


